name: showman
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  pinput: ^2.2.11
  carousel_slider: ^4.1.1
  custom_radio_grouped_button: ^2.1.2+2
  page_transition: ^2.0.9
  fluttertoast: ^8.0.9
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: assets/fonts/MyFlutterApp.ttf
    - family: MyIcons
      fonts:
        - asset: assets/fonts/MyIcons.ttf